#!/usr/bin/expect -f

# set timeout -1

spawn /usr/bin/pcloudcc -u $env(PCLOUD_USERNAME) -s -m $env(PCLOUD_MOUNT)
expect "pCloud console client v.2.0.1"
expect "Down: Everything Downloaded| Up: Everything Uploaded, status is LOGIN_REQUIRED"
expect "Please, enter password" {send "$env(PCLOUD_PASSWORD)\r"}
expect "logging in"
expect "Down: Everything Downloaded| Up: Everything Uploaded, status is READY"
